# Generated by Django 4.2.6 on 2023-10-18 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoderadoSuplente1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Apoderado Suplente 1',
                'verbose_name_plural': 'Apoderados Suplentes 1',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoSuplente2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Apoderado Suplente 2',
                'verbose_name_plural': 'Apoderados Suplentes 2',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('etnia', models.CharField(choices=[('No posee', 'No posee'), ('Aymara', 'Aymara'), ('Lickanantay', ' Lickanantay'), ('Colla', 'Colla'), ('Quechua', 'Quechua'), ('Diaguita', 'Diaguita'), ('Chango', 'Chango'), ('Rapa Nui', 'Rapa Nui'), ('Mapuche', 'Mapuche'), ('Kawesqar', 'Kawesqar'), ('Yagan', 'Yagan')], default='No Posee', max_length=100, verbose_name='Ascendencia')),
                ('salud', models.CharField(choices=[('Seleccione', 'Seleccione'), ('Publica', 'Publica'), ('Privada', 'Privada')], default='Seleccione', max_length=100, verbose_name='Salud')),
                ('renta', models.PositiveIntegerField(verbose_name='Renta')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Apoderado Titular',
                'verbose_name_plural': 'Apoderados Titulares',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('letra_curso', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Letra')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('etnia', models.CharField(choices=[('No posee', 'No posee'), ('Aymara', 'Aymara'), ('Lickanantay', ' Lickanantay'), ('Colla', 'Colla'), ('Quechua', 'Quechua'), ('Diaguita', 'Diaguita'), ('Chango', 'Chango'), ('Rapa Nui', 'Rapa Nui'), ('Mapuche', 'Mapuche'), ('Kawesqar', 'Kawesqar'), ('Yagan', 'Yagan')], default='No Posee', max_length=100, verbose_name='Ascendencia')),
                ('comorbilidad', models.TextField(verbose_name='Comorbilidad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nivel Academico')),
            ],
            options={
                'verbose_name': 'Nivel Academico',
                'verbose_name_plural': 'Niveles Academicos',
            },
        ),
        migrations.CreateModel(
            name='RegistroPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, null=True, verbose_name='Alumno Regular')),
                ('ApoderadoSuplente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apoderadosuplente1', verbose_name='Apoderado Suplente 1')),
                ('ApoderadoSuplente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apoderadosuplente2', verbose_name='Apoderado Suplente 2')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apoderadotitular', verbose_name='Apoderado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pie',
                'verbose_name_plural': 'Pies',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nivelacademico'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_entrada', models.TimeField(auto_now=True)),
                ('hora_salida', models.TimeField(auto_now=True)),
                ('bloque1', models.CharField(choices=[('Primer bloque', 'Primer bloque'), ('Segundo bloque', 'Segundo bloque')], default='Primer bloque', max_length=20, verbose_name='Bloque')),
                ('objetivoClase1', models.CharField(max_length=350, verbose_name='Objetivo de la Clase')),
                ('objetivoPaci1', models.CharField(max_length=350, verbose_name='Objetivo del Paci')),
                ('desarrolloActividad1', models.TextField(verbose_name='Desarrollo de la actividad')),
                ('material1', models.TextField(verbose_name='Material utilizado')),
                ('personaMaterial1', models.CharField(max_length=100, verbose_name='Persona que entrega el material')),
                ('reaccion1', models.CharField(max_length=350, verbose_name='Reaccion del alumno frente a la actividad')),
                ('estadoAprendizaje1', models.CharField(choices=[('Seleccione', 'Seleccione'), ('No logrado', 'No logrado'), ('Via de logro', 'Via de logro'), ('Logrado', 'Logrado')], default='Selecione', max_length=20, verbose_name='Estado aprendizaje')),
                ('apoyoDocente1', models.CharField(choices=[('Seleccione', 'Seleccione'), ('Si', 'Si'), ('No', 'No')], default='Seleccione', max_length=20, verbose_name='Apoyo del Docente durante la actividad')),
                ('obervacionesGenerales1', models.TextField(verbose_name='Observaciones generales')),
                ('bloque2b', models.CharField(choices=[('Primer bloque', 'Primer bloque'), ('Segundo bloque', 'Segundo bloque')], default='Segundo bloque', max_length=20, verbose_name='Bloque')),
                ('objetivoClase2b', models.CharField(max_length=350, verbose_name='Objetivo de la Clase')),
                ('objetivoPaci2b', models.CharField(max_length=350, verbose_name='Objetivo del Paci')),
                ('desarrolloActividad2b', models.TextField(verbose_name='Desarrollo de la actividad')),
                ('material2b', models.TextField(verbose_name='Material utilizado')),
                ('personaMaterial2b', models.CharField(max_length=100, verbose_name='Persona que entrega el material')),
                ('reaccion2b', models.CharField(max_length=350, verbose_name='Reaccion del alumno frente a la actividad')),
                ('estadoAprendizaje2b', models.CharField(choices=[('Seleccione', 'Seleccione'), ('No logrado', 'No logrado'), ('Via de logro', 'Via de logro'), ('Logrado', 'Logrado')], default='Selecione', max_length=20, verbose_name='Estado aprendizaje')),
                ('apoyoDocente2b', models.CharField(choices=[('Seleccione', 'Seleccione'), ('Si', 'Si'), ('No', 'No')], default='Seleccione', max_length=20, verbose_name='Apoyo del Docente durante la actividad')),
                ('obervacionesGenerales2b', models.TextField(verbose_name='Observaciones generales')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('presente', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('curso', models.ForeignKey(limit_choices_to={'id': 1}, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
