# Generated by Django 4.2.6 on 2023-12-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(choices=[('Educación Parvularia', 'Educación Parvularia'), ('Primer Ciclo Básico', 'Primer Ciclo Básico'), ('Segundo Ciclo Básico', 'Segundo Ciclo Básico')], max_length=100, verbose_name='Nivel Académico')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('letra_curso', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Letra')),
                ('enable', models.BooleanField(default=True, null=True, verbose_name='Alumno Regular')),
                ('ApoderadoSuplente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadosuplente1', verbose_name='Apoderado Suplente 1')),
                ('ApoderadoSuplente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadosuplente2', verbose_name='Apoderado Suplente 2')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadotitular', verbose_name='Apoderado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pie',
                'verbose_name_plural': 'Pies',
            },
        ),
    ]
