# Generated by Django 5.1.4 on 2024-12-12 15:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Área Académica')),
            ],
            options={
                'verbose_name': 'Área Académica',
                'verbose_name_plural': 'Áreas Académicas',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura:')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('area_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.areaacademica', verbose_name='Área Académica')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('nee', models.CharField(choices=[('Transitorio', 'Transitorio'), ('Permanente', 'Permanente')], max_length=100, verbose_name='Necesidades Educativas')),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('etnia', models.CharField(choices=[('No posee', 'No posee'), ('Aymara', 'Aymara'), ('Lickanantay', ' Lickanantay'), ('Colla', 'Colla'), ('Quechua', 'Quechua'), ('Diaguita', 'Diaguita'), ('Chango', 'Chango'), ('Rapa Nui', 'Rapa Nui'), ('Mapuche', 'Mapuche'), ('Kawesqar', 'Kawesqar'), ('Yagan', 'Yagan')], default='No Posee', max_length=100, verbose_name='Ascendencia')),
                ('comorbilidad', models.TextField(verbose_name='Comorbilidad')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.curso', verbose_name='Curso')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='BitacoraEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha:')),
                ('aula', models.CharField(choices=[('Dentro del aula', 'Dentro del aula'), ('Fuera del aula', 'Fuera del aula')], max_length=100, verbose_name='Aula:')),
                ('horas_estudiante', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Horas Estudiante:')),
                ('actividad', models.TextField(blank=True, verbose_name='Actividad:')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones:')),
                ('nivelLogro', models.BooleanField(default=False, verbose_name='Nivel de Logro (True = Logrado, False = En Vías de Logro)')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitácoras_asignatura', to='estudiantes.asignatura', verbose_name='Asignatura:')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitácoras_profesional', to='accounts.profile', verbose_name='Profesional:')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitácoras_estudiante', to='estudiantes.estudiante', verbose_name='Estudiante:')),
            ],
        ),
        migrations.CreateModel(
            name='ApoderadoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('etnia', models.CharField(blank=True, choices=[('No posee', 'No posee'), ('Aymara', 'Aymara'), ('Lickanantay', ' Lickanantay'), ('Colla', 'Colla'), ('Quechua', 'Quechua'), ('Diaguita', 'Diaguita'), ('Chango', 'Chango'), ('Rapa Nui', 'Rapa Nui'), ('Mapuche', 'Mapuche'), ('Kawesqar', 'Kawesqar'), ('Yagan', 'Yagan')], default='No Posee', max_length=100, null=True, verbose_name='Ascendencia')),
                ('salud', models.CharField(blank=True, choices=[('Seleccione', 'Seleccione'), ('Publica', 'Publica'), ('Privada', 'Privada')], default='Seleccione', max_length=100, null=True, verbose_name='Salud')),
                ('renta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Renta')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Apoderado Titular',
                'verbose_name_plural': 'Apoderados Titulares',
            },
        ),
        migrations.CreateModel(
            name='AnamnesisEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('pais_natal', models.CharField(blank=True, choices=[('Seleccione País', 'Seleccione País'), ('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('República Dominicana', 'República Dominicana'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela'), ('Otros', 'Otros')], default='Seleccione País', max_length=150, null=True, verbose_name='País Natal')),
                ('sexo', models.CharField(blank=True, choices=[('Selecciones Sexo', 'Seleccione Sexo'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Seleccione Sexo', max_length=150, null=True, verbose_name='Sexo')),
                ('lengua', models.CharField(blank=True, choices=[('Seleccione Lengua', 'Seleccione Lengua'), ('Español', 'Español'), ('Ingles', 'Ingles'), ('Chino', 'Chino'), ('Aymara', 'Aymara'), ('Quechua', 'Quechua'), ('Mapudungu', 'Mapudungu')], default='Seleccione Lengua', max_length=150, null=True, verbose_name='Lengua de uso')),
                ('alumno_trabajador', models.BooleanField(blank=True, default=False, null=True, verbose_name='Alumno Trabajador (True = Sí, False = No)')),
                ('fecha_entrevista', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Entrevista')),
                ('definicion_problema', models.TextField(blank=True, null=True, verbose_name='Definición del Problema o Situación que Motiva la Entrevista')),
                ('pediatria', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pediatría (True = Sí, False = No)')),
                ('kinesiologia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Kinesiología (True = Sí, False = No)')),
                ('genetico', models.BooleanField(blank=True, default=False, null=True, verbose_name='Genético (True = Sí, False = No)')),
                ('fonoaudiologia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Fonoaudiología (True = Sí, False = No)')),
                ('neurologia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Neurología (True = Sí, False = No)')),
                ('psicologia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Psicología (True = Sí, False = No)')),
                ('psiquiatria', models.BooleanField(blank=True, default=False, null=True, verbose_name='Psiquiatría (True = Sí, False = No)')),
                ('psicopedagogia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Psicopedagogía (True = Sí, False = No)')),
                ('terapia_ocupacional', models.BooleanField(blank=True, default=False, null=True, verbose_name='Terapia Ocupacional (True = Sí, False = No)')),
                ('otro', models.BooleanField(blank=True, default=False, null=True, verbose_name='Otro (True = Sí, False = No)')),
                ('perdida_auditiva', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pérdida Auditiva (True = Sí, False = No)')),
                ('perdida_visual', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pérdida Visual (True = Sí, False = No)')),
                ('motor', models.BooleanField(blank=True, default=False, null=True, verbose_name='Motor (True = Sí, False = No)')),
                ('paraplejia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Paraplejia (True = Sí, False = No)')),
                ('trastorno_conductual', models.BooleanField(blank=True, default=False, null=True, verbose_name='Trastorno Conductual (True = Sí, False = No)')),
                ('otros', models.TextField(blank=True, null=True, verbose_name='Otros')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('entrevistador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Entrevistador')),
                ('curso_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.curso', verbose_name='Curso Actual')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=350, null=True, verbose_name='Nombre')),
                ('parentesco', models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Otro', 'Otro')], max_length=150, null=True, verbose_name='Parentesco')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[estudiantes.models.validate_edad], verbose_name='Edad')),
                ('escolaridad', models.CharField(blank=True, max_length=350, null=True, verbose_name='Escolaridad')),
                ('ocupacion_actual', models.CharField(blank=True, max_length=350, null=True, verbose_name='Ocupación Actual')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='estudiantes.anamnesisestudiante', verbose_name='Anamnesis')),
            ],
        ),
        migrations.CreateModel(
            name='Paci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('Selecciones Sexo', 'Seleccione Sexo'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=150, null=True, verbose_name='Sexo')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('fecha_elaboracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Elaboración')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('duracion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (en meses)')),
                ('antecedentes_salud', models.TextField(blank=True, null=True, verbose_name='Antecedentes Relevantes de Salud')),
                ('antecedentes_escolares', models.TextField(blank=True, null=True, verbose_name='Antecedentes Escolares')),
                ('antecedentes_familiares', models.TextField(blank=True, null=True, verbose_name='Antecedentes Familiares (Con quien vive)')),
                ('expectativas', models.TextField(blank=True, null=True, verbose_name='Expectativas, Sueños y Prioridades de la Familia')),
                ('apoyos', models.TextField(blank=True, null=True, verbose_name='Apoyos que se requieren para lograrlo')),
                ('rbd', models.CharField(blank=True, max_length=150, null=True, verbose_name='RBD')),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre del Establecimiento')),
                ('jefe_utp', models.CharField(blank=True, max_length=350, null=True, verbose_name='Jefe UTP')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('coordinador_pie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Coordinador PIE')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.curso', verbose_name='Curso')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_tiempo', models.TextField(blank=True, null=True, verbose_name='Organización del tiempo y el horario')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacion_tiempo', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivosAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_ensenanza', models.CharField(blank=True, choices=[('Educación Básica', 'Educación Básica'), ('Educación Media', 'Educación Media')], max_length=150, null=True, verbose_name='Nivel de Enseñanza')),
                ('curso', models.CharField(blank=True, max_length=350, null=True, verbose_name='Curso')),
                ('asignatura_o_nucleo', models.CharField(blank=True, max_length=350, null=True, verbose_name='Asignatura o Núcleo')),
                ('eje_o_ambito', models.CharField(blank=True, max_length=350, null=True, verbose_name='Eje o Ámbito')),
                ('espacio_educativo', models.CharField(blank=True, max_length=350, null=True, verbose_name='Contexto o Espacio Educativo')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_aprendizaje', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='MultiplesMedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiples_medios', models.TextField(blank=True, null=True, verbose_name='Proporcionar múltiples medios de participación y compromiso')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiples_medios', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='MediosEjecucionExpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medios_ejecucion_expresion', models.TextField(blank=True, null=True, verbose_name='Medios de Ejecución y Expresión')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_ejecucion_expresion', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='GraduacionComplejidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacion_complejidad', models.TextField(blank=True, null=True, verbose_name='Graduación del nivel de complejidad')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacion_complejidad', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaPaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firma_paci', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoResponsablePaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=350, null=True, verbose_name='Nombre')),
                ('profesion', models.CharField(blank=True, choices=[('Coordinador PIE', 'Coordinador PIE'), ('Jefe UTP', 'Jefe UTP'), ('Psicopedagogo', 'Psicopedagogo'), ('Psicólogo', 'Psicólogo'), ('Fonoaudiólogo', 'Fonoaudiólogo'), ('Kinesiólogo', 'Kinesiólogo'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Docente Educación Especial/Diferencial', 'Docente Educación Especial/Diferencial'), ('Docente de Asignatura', 'Docente de Asignatura'), ('Otro', 'Otro')], max_length=150, null=True, verbose_name='Profesión')),
                ('funcion', models.TextField(blank=True, null=True, verbose_name='Función')),
                ('n_registro', models.CharField(blank=True, max_length=150, null=True, verbose_name='N° Registro')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_responsable', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='Entorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entorno', models.TextField(blank=True, null=True, verbose_name='Entorno (Adecuación en los espacios, ubicación y condiciones)')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entorno', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='EnriquecimientoCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enriquecimiento_curriculum', models.TextField(blank=True, null=True, verbose_name='Enriquecimiento del Curriculum')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enriquecimiento_curriculum', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='CritEvaluacionPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios', models.TextField(blank=True, null=True, verbose_name='Aspectos a Considerar')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crit_evaluacion_promocion', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnasObjetivosAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código')),
                ('objetivos_aprendizaje', models.TextField(blank=True, null=True, verbose_name='Objetivos de Aprendizaje Priorizados')),
                ('adaptacion_de_oa', models.TextField(blank=True, null=True, verbose_name='Adaptación de OA')),
                ('estrategias_metodologicas', models.TextField(blank=True, null=True, verbose_name='Estrategias Metodológicas')),
                ('evaluacion_de_oa', models.TextField(blank=True, null=True, verbose_name='Evaluación de OA')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas_objetivos_aprendizaje', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboracionFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspectos_familia', models.TextField(blank=True, null=True, verbose_name='Aspectos a Considerar')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboracion_familia', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='AulaRegular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula_regular', models.TextField(blank=True, null=True, verbose_name='Aula Regular')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_regular', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='AulaRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula_de_recursos', models.TextField(blank=True, null=True, verbose_name='Aula de Recursos')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_recursos', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('sexo', models.CharField(blank=True, choices=[('Selecciones Sexo', 'Seleccione Sexo'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=150, null=True, verbose_name='Sexo')),
                ('fecha_elaboracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Elaboración')),
                ('rbd', models.CharField(blank=True, max_length=150, null=True, verbose_name='RBD')),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre del Establecimiento')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('coordinador_pie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Coordinador PIE')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.curso', verbose_name='Curso')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioApoyos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Día')),
                ('horario', models.CharField(blank=True, max_length=350, null=True, verbose_name='Horario')),
                ('contexto', models.CharField(blank=True, max_length=350, null=True, verbose_name='Contexto')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Profesional')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_apoyos', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=350, null=True, verbose_name='Nombres')),
                ('parentesco', models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Otro', 'Otro')], max_length=150, null=True, verbose_name='Parentesco')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familia', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiasDiversificadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.TextField(blank=True, null=True, verbose_name='Criterio')),
                ('estrategias', models.TextField(blank=True, null=True, verbose_name='Estrategias para')),
                ('metodo', models.TextField(blank=True, null=True, verbose_name='Método')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias_diversificadas', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoResponsablePai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesional', models.CharField(blank=True, max_length=350, null=True, verbose_name='Nombre Profesional')),
                ('cargo', models.CharField(blank=True, choices=[('Coordinador PIE', 'Coordinador PIE'), ('Jefe UTP', 'Jefe UTP'), ('Psicopedagogo', 'Psicopedagogo'), ('Psicólogo', 'Psicólogo'), ('Fonoaudiólogo', 'Fonoaudiólogo'), ('Kinesiólogo', 'Kinesiólogo'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Docente Educación Especial/Diferencial', 'Docente Educación Especial/Diferencial'), ('Docente de Asignatura', 'Docente de Asignatura'), ('Otro', 'Otro')], max_length=250, null=True, verbose_name='Cargo')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_responsable', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('profesion', models.CharField(blank=True, choices=[('Docente Matemáticas', 'Docente Matemáticas'), ('Docente Lenguaje', 'Docente Lenguaje'), ('Docente Historia', 'Docente Historia'), ('Docente Ciencias', 'Docente Ciencias'), ('Docente Educación Física', 'Docente Educación Física'), ('Docente Tecnología', 'Docente Tecnología'), ('Docente Inglés', 'Docente Inglés'), ('Docente Filosofía', 'Docente Filosofía'), ('Docente Orientación', 'Docente Orientación'), ('Docente', 'Docente'), ('Docente Otro', 'Docente Otro')], max_length=150, null=True, verbose_name='Profesión')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyosEspecializados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('contexto', models.TextField(blank=True, null=True, verbose_name='Contexto')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoyos_especializados', to='estudiantes.pai', verbose_name='PAI')),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionRepresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion_representacion', models.TextField(blank=True, null=True, verbose_name='Presentación y Representación de la Información')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_representacion', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='PriorizacionOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorizacion_oa', models.TextField(blank=True, null=True, verbose_name='Priorización de OA y contenidos')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorizacion_oa', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dia', models.FloatField(default=0.0, verbose_name='Total del Día (%)')),
                ('bitacora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.bitacoraestudiante', verbose_name='Bitácora')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioMensualHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_mes', models.DateField(verbose_name='Inicio del Mes')),
                ('fin_mes', models.DateField(verbose_name='Fin del Mes')),
                ('promedio_mes', models.FloatField(default=0.0, verbose_name='Promedio del Mes (%)')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioSemanalHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_semana', models.DateField(verbose_name='Inicio de la Semana')),
                ('fin_semana', models.DateField(verbose_name='Fin de la Semana')),
                ('promedio_semana', models.FloatField(default=0.0, verbose_name='Promedio de la Semana (%)')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoPaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimiento', models.TextField(blank=True, null=True, verbose_name='Aspectos a Considerar')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_paci', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
        migrations.CreateModel(
            name='Temporalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporalizacion', models.TextField(blank=True, null=True, verbose_name='Temporalización')),
                ('paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporalizacion', to='estudiantes.paci', verbose_name='PACI')),
            ],
        ),
    ]
